import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl text-center mt-2 uppercase text-blue-400">Next Template</h1>
        <h2 className="text-3xl text-orange-400 text-center">New tailwind colors</h2>
        <h2 className="text-3xl text-amber-200 text-center line-through decoration-black decoration-4">New tailwind colors</h2>
        <h2 className="text-3xl text-sky-600 text-center underline decoration-solid">New tailwind colors</h2>
        <h2 className="text-3xl text-cyan-500 text-center decoration-wavy decoration-teal-400 ">New tailwind colors</h2>
        <h2 className="text-3xl text-emerald-700 text-center">New tailwind colors</h2>
        <h2 className="text-3xl text-pink-400 text-center underline decoration-wavy">New tailwind colors</h2>
        <h2 className="text-3xl text-lime-400 text-center underline decoration-dashed decoration-sky-600">New tailwind colors</h2>
        <h2 className="text-3xl text-emerald-400 text-center">New tailwind colors</h2>
        <h2 className="text-3xl text-fuchsia-700 text-center">New tailwind colors</h2>
        <h2 className="text-3xl text-rose-300 text-center">New tailwind colors</h2>
        <h2 className="text-3xl text-slate-300 text-center decoration-double underline decoration-sky-400 ">New tailwind colors</h2>
        <h2 className="text-3xl text-red-600 text-center">New tailwind colors</h2>
        
      </main>
      
    </div>
  )
}
